<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>MacroLauncher</AssemblyName>
    <RootNamespace>MacroLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MacroCore\MacroCore.csproj" />
  </ItemGroup>
</Project>
